version: '3.8'
services:

  #
  # The Identity Server uses a simple in memory database
  #
  identity-server:
    image: curity.azurecr.io/curity/idsvr:6.4.2
    hostname: identityserver.example.internal
    ports:
     - 6749:6749
     - 8443:8443
    volumes:
     - ./idsvr/license.json:/opt/idsvr/etc/init/license/license.json
     - ./idsvr/config-backup.xml:/opt/idsvr/etc/init/config.xml
    environment:
      PASSWORD: 'Password1'

  #
  # The API Gateway terminates TLS for API calls
  #
  api-gateway:
    image: kong:2.5.0-alpine
    hostname: apigateway.example.internal
    ports:
      - 3000:3000
    volumes:
      - ./api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:3000'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled'
